# Avalon Tournament Configuration
name: "Avalon Tournament"
game: "avalon"

# Game-specific settings
game_config:
  n_players: 7  # 7 players: 4 good, 3 evil
  seed: null
  include_merlin: true
  include_percival: false
  include_morgana: false
  include_mordred: false
  include_oberon: false

# Schedule file (CSV with role assignments)
schedule_file: "configs/tournaments/avalon-equalizer.csv"
schedule_format: "avalon"  # Format: game_id,players,good,evil

# Output settings
output_dir: "experiments/tournaments/avalon"
log_games: true
log_private_info: true

# Execution settings
max_concurrent_games: 42
timeout_per_game: 7200  # seconds (1 hour)

# Model name mappings
model_mapping:
  grok-4: "x-ai/grok-4"
  claude-opus-4.1: "anthropic/claude-opus-4.1"
  claude-opus-4: "anthropic/claude-opus-4"
  claude-sonnet-4.5: "anthropic/claude-4.5-sonnet"
  claude-sonnet-4.5-a: "anthropic/claude-4.5-sonnet"
  claude-sonnet-4.5-b: "anthropic/claude-4.5-sonnet"
  gpt-5: "openai/gpt-5"
  gpt-4o: "openai/gpt-4o"
  gemini-2.5-pro: "google/gemini-2.5-pro"
  gemini-2.0-flash: "google/gemini-2.0-flash"
  kimi-k2-0905: "moonshotai/kimi-k2-0905"
  qwen3-235b-a22b: "qwen/qwen3-235b-a22b"
  llama-4-maverick: "meta-llama/llama-4-maverick"
  glm-4.5: "z-ai/glm-4.5"

# Agent settings
agent_config:
  type: "OpenRouterAgent"
  temperature: 0.7
  max_tokens: 8192
  timeout: 60

# Metrics to track
metrics:
  - "win_rate"
  - "good_win_rate"
  - "evil_win_rate"
  - "mission_success_rate"
  - "team_proposal_success_rate"
  - "assassination_success_rate"

