# Secret Hitler Tournament Configuration
name: "Secret Hitler Tournament"
game: "secret_hitler"

# Game-specific settings
game_config:
  n_players: 7  # Minimum for Secret Hitler (3 Liberals, 1 Fascist, 1 Hitler)
  seed: null
  log_private_info: true

# Schedule file (CSV with role assignments)
schedule_file: "configs/tournaments/secret_hitler_grok_tournament_schedule.csv"
schedule_format: "secret_hitler"  # Format: game_id,liberals,fascists

# Output settings
output_dir: "experiments/tournaments/secret_hitler"
log_games: true
log_private_info: true

# Execution settings
max_concurrent_games: 18
timeout_per_game: 3600  # seconds (1 hour)

# Model name mappings
model_mapping:
  grok-4: "x-ai/grok-4"
  claude-opus-4.1: "anthropic/claude-opus-4.1"
  claude-opus-4: "anthropic/claude-opus-4"
  claude-sonnet-4.5: "anthropic/claude-4.5-sonnet"
  gpt-5: "openai/gpt-5"
  gpt-4o: "openai/gpt-4o"
  gemini-2.5-pro: "google/gemini-2.5-pro"
  gemini-2.0-flash: "google/gemini-2.0-flash"
  kimi-k2-0905: "moonshotai/kimi-k2-0905"
  qwen3-235b-a22b: "qwen/qwen3-235b-a22b"
  llama-4-maverick: "meta-llama/llama-4-maverick"
  glm-4.5: "z-ai/glm-4.5"

# Agent settings
agent_config:
  type: "OpenRouterAgent"
  temperature: 0.7
  max_tokens: 4096
  timeout: 60

# Metrics to track
metrics:
  - "win_rate"
  - "liberal_win_rate"
  - "fascist_win_rate"
  - "policies_enacted"
  - "execution_accuracy"
  - "hitler_election_rate"

