# Sheriff of Nottingham Tournament Configuration
name: "Sheriff of Nottingham Tournament"
game: "sheriff"

# Game-specific settings
game_config:
  n_players: 4
  max_rounds: 2
  starting_coins: 50
  legal_goods_payment: true
  contraband_penalties: true
  enable_bribes: true

# Schedule file (CSV with player assignments)
schedule_file: "configs/tournaments/sheriff_grok_tournament_final.csv"
schedule_format: "sheriff"  # Format: game_id,player1,player2,player3,player4

# Output settings
output_dir: "experiments/tournaments/sheriff"
log_games: true
log_private_info: true

# Execution settings
max_concurrent_games: 16
timeout_per_game: 3600  # seconds (1 hour)

# Model name mappings
model_mapping:
  grok-4: "x-ai/grok-4"
  claude-opus-4.1: "anthropic/claude-opus-4.1"
  claude-opus-4: "anthropic/claude-opus-4"
  claude-sonnet-4.5: "anthropic/claude-4.5-sonnet"
  gpt-5: "openai/gpt-5"
  gpt-4o: "openai/gpt-4o"
  gemini-2.5-pro: "google/gemini-2.5-pro"
  gemini-2.0-flash: "google/gemini-2.0-flash"
  kimi-k2-0905: "moonshotai/kimi-k2-0905"
  qwen3-235b-a22b: "qwen/qwen3-235b-a22b"
  llama-4-maverick: "meta-llama/llama-4-maverick"
  glm-4.5: "z-ai/glm-4.5"

# Agent settings
agent_config:
  type: "OpenRouterAgent"
  temperature: 0.7
  max_tokens: 4096
  timeout: 60

# Metrics to track
metrics:
  - "win_rate"
  - "average_coins"
  - "smuggling_success_rate"
  - "inspection_accuracy"
  - "bribe_success_rate"

