# Mini Secret Hitler Tournament for Testing (3 games only)
name: "Secret Hitler Mini Test Tournament"
game: "secret_hitler"

# Game-specific settings
game_config:
  n_players: 5  # Minimum for Secret Hitler (3 Liberals, 1 Fascist, 1 Hitler)
  seed: null
  log_private_info: true

# Schedule file
schedule_file: "configs/tournaments/test_secret_hitler_mini_schedule.csv"
schedule_format: "secret_hitler"  # Format: Round,Game,Player_1,Player_2,Player_3,Player_4,Player_5

# Output settings
output_dir: "experiments/tournaments/test_secret_hitler_mini"
log_games: true
log_private_info: true

# Execution settings
max_concurrent_games: 3  # Run all games in parallel
timeout_per_game: 1800  # 30 minutes max per game

# Model name mappings
model_mapping:
  claude-sonnet-4.5: "anthropic/claude-3.5-sonnet"
  gpt-4o: "openai/gpt-4o"
  gpt-5: "openai/gpt-5"

# Agent settings
agent_config:
  type: "OpenRouterAgent"
  temperature: 0.7
  max_tokens: 4096
  timeout: 60

# Metrics to track
metrics:
  - "win_rate"
  - "liberal_win_rate"
  - "fascist_win_rate"
  - "policies_enacted"
  - "execution_accuracy"
  - "hitler_election_rate"


