# Mini Among Us Tournament for Testing (2 games only)
name: "Among Us Mini Test Tournament"
game: "among_us"

# Game-specific settings
game_config:
  n_players: 6  # Will be overridden by schedule
  n_impostors: 2
  tasks_per_player: 4  # Tasks each crewmate must complete
  max_task_rounds: 30  # Shorter for testing (default: 100)
  discussion_rounds: 2  # Fewer rounds for speed (default: 5)
  emergency_meetings: 1  # Per player (default: 2)
  kill_cooldown: 2  # Rounds between kills (default: 3)

# Schedule file (create a mini version)
schedule_file: "configs/tournaments/test_amongus_mini_schedule.csv"
schedule_format: "amongus"

# Output settings
output_dir: "experiments/tournaments/test_amongus_mini"
log_games: true
log_private_info: true

# Execution settings
max_concurrent_games: 2  # Run both games in parallel
timeout_per_game: 600  # 10 minutes max per game

# Model name mappings
model_mapping:
  claude-sonnet-4.5: "anthropic/claude-3.5-sonnet"
  gpt-4o: "openai/gpt-4o"

# Agent settings
agent_config:
  type: "OpenRouterAgent"
  temperature: 0.7
  max_tokens: 4096
  timeout: 60

# Metrics to track
metrics:
  - "win_rate"
  - "impostor_win_rate"
  - "crewmate_win_rate"
  - "task_completion_rate"
  - "survival_rate"
  - "kills_per_impostor"

