# Werewolf Tournament Configuration
name: "Werewolf Tournament"
game: "werewolf"

# Game-specific settings
game_config:
  n_players: 6  # Total players (will be overridden by schedule)
  n_werewolves: 2
  max_rounds: 50
  day_discussion_rounds: 3
  enable_seer: true
  enable_doctor: false
  discussion_time_limit: null

# Schedule file (CSV with role assignments)
schedule_file: "configs/tournaments/werewolf_tournament_schedule.csv"
schedule_format: "werewolf"  # Format: game_id,villager_model,werewolf_model

# Output settings
output_dir: "experiments/tournaments/werewolf"
log_games: true
log_private_info: true

# Execution settings
max_concurrent_games: 3
timeout_per_game: 3600  # seconds (1 hour)

# Model name mappings
model_mapping:
  claude-opus-4.1: "anthropic/claude-opus-4.1"
  claude-opus-4: "anthropic/claude-opus-4"
  claude-sonnet-4.5: "anthropic/claude-3.5-sonnet"
  gpt-5: "openai/gpt-5"
  gpt-4o: "openai/gpt-4o"
  gemini-2.5-pro: "google/gemini-2.5-pro"
  gemini-2.0-flash: "google/gemini-2.0-flash"
  kimi-k2-0905: "moonshotai/kimi-k2-0905"
  qwen3-235b-a22b: "qwen/qwen3-235b-a22b"
  llama-4-maverick: "meta-llama/llama-4-maverick"
  glm-4.5: "z-ai/glm-4.5"

# Agent settings
agent_config:
  type: "OpenRouterAgent"
  temperature: 0.7
  max_tokens: 4096
  timeout: 60

# Metrics to track
metrics:
  - "win_rate"
  - "villager_win_rate"
  - "werewolf_win_rate"
  - "survival_rate"
  - "vote_accuracy"
  - "kills_per_werewolf"

