# Secret Hitler Game Configuration

game: secret_hitler

# Number of players (5-10)
n_players: 5

# Game parameters
seed: null

# LLM Agent Settings
agent:
  model: "openai/gpt-4o-mini"
  temperature: 0.8
  memory_capacity: 30
  
# Logging
logging:
  enabled: true
  output_dir: "experiments/secret_hitler"
  log_private: true  # Save private info (roles, observations) for analysis
